source "https://rubygems.org"

ruby "3.4.5"

gem "completion-kit", path: "../"
gem "solid_queue"
gem "solid_cable"
gem "mission_control-jobs"
gem "puma"
gem "sqlite3"
gem "propshaft"
gem "bootsnap", require: false
gem "dotenv-rails"

group :production do
  gem "pg"
end
