source "https://rubygems.org"

ruby "3.3.5"

gem "completion-kit", path: "../"
gem "puma"
gem "sqlite3"
gem "sprockets-rails"
gem "bootsnap", require: false
gem "dotenv-rails"

group :production do
  gem "pg"
end
