default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <% if ENV["DATABASE_URL"] %>
  url: <%= ENV["DATABASE_URL"] %>
  prepared_statements: false
  <% else %>
  <<: *default
  database: db/production.sqlite3
  <% end %>
