default: &default
  adapter: sqlite3
  pool: <%= [ENV.fetch("RAILS_MAX_THREADS", 5).to_i, ENV.fetch("SOLID_QUEUE_THREADS", 10).to_i + 2].max %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <% if ENV["DATABASE_URL"] %>
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  prepared_statements: false
  pool: <%= [ENV.fetch("RAILS_MAX_THREADS", 5).to_i, ENV.fetch("SOLID_QUEUE_THREADS", 10).to_i + 2].max %>
  <% else %>
  <<: *default
  database: db/production.sqlite3
  <% end %>
